Fi ass2 rohan
dexplat/flutter-interns-summers-23 pull request #37
Opened 2023-07-21 04:33 UTC by Rohankhan5990

# f1-as2-rohankhan

## Changes Proposed
- Login Page Created
- Home Page Created
- Profile Page Created

## Checks
- [x] added a reviewer 
- [ ] PR is reviewed 

# ScreenShots
![login](https://github.com/dexplat/flutter-interns-summers-23/assets/134016581/d9dd89e1-defd-45a9-9817-ad12069ce3a8)
![home](https://github.com/dexplat/flutter-interns-summers-23/assets/134016581/e02196f1-3320-4f20-ae8b-33bc51a9c67c)
![profile](https://github.com/dexplat/flutter-interns-summers-23/assets/134016581/bc7d991f-72d6-4040-a970-cb28678fb9ee)

2023-07-21 09:56 UTC, mhmzdev requested changes

2023-07-21 09:56 UTC, mhmzdev commented on assets/fi_ass2_rohan_assets/Coment.png
use svgs for icons

2023-07-21 09:56 UTC, mhmzdev commented on assets/fi_ass2_rohan_assets/Coment.png
folders names must be `lower_snake_case`

2023-07-21 09:56 UTC, mhmzdev commented on assets/fi_ass2_rohan_assets/Coment.png
update file names to format `fi_a2_your_name.dart` and widgets as well `FiA2YourName`

2023-07-21 09:56 UTC, mhmzdev commented on lib/assesments/assessment_2/fi_ass2_rohan/Home/fi_ass2_rohan_home.dart
> +  int i = 0;
give this proper name

2023-07-21 09:56 UTC, mhmzdev commented on lib/assesments/assessment_2/fi_ass2_rohan/Home/fi_ass2_rohan_home.dart
> +                  InkWell(
You can use `map` or `for` loop for this rendering of widgets

2023-07-21 09:57 UTC, mhmzdev commented
Also please update the title of pr as per format

2023-07-21 10:15 UTC, ahmadexe requested changes

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Home/fi_ass2_rohan_home.dart
> +  int i = 0;
please use proper names like index, tabIndex etc

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Home/fi_ass2_rohan_home.dart
> +                          borderRadius: BorderRadius.circular(50)),
Please add tailing commas and format the file

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Home/fi_ass2_rohan_home.dart
> +                        const Padding(
Never use padding to add spaces, used SizedBox(width: somewidth);

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Home/fi_ass2_rohan_home.dart
> +                          padding: EdgeInsets.only(left: 5),
Use sizedbox

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Home/fi_ass2_rohan_home.dart
> +                          padding: EdgeInsets.only(left: 55),
Instead of doing this, wrap this in expanded

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Widgets/SizedBox/fi_ass2_rohan_size.dart
> +Widget rohanSmallSizedBox5 = const SizedBox(
use const  at the start 
```const Widget rohanSmallSizedBox = SizedBox();```

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Widgets/SizedBox/fi_ass2_rohan_size.dart
> +Widget rohanSmallSizedBox4 = const SizedBox(
same as above

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Widgets/SizedBox/fi_ass2_rohan_size.dart
> +Widget rohanSmallSizedBox3 = const SizedBox(
same as above

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Widgets/SizedBox/fi_ass2_rohan_size.dart
> +Widget rohanSmallSizedBox2 = const SizedBox(
same as above

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Widgets/SizedBox/fi_ass2_rohan_size.dart
> +Widget rohanSmallSizedBox1 = const SizedBox(
same as above

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/fi_ass2_rohan_login.dart
> +    Widget smallSpace = const SizedBox(
```const Widget smallSpace = SizedBox();```

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/fi_ass2_rohan_login.dart
> +    Widget smallSpace = const SizedBox(
PS If you're using this at multiple places why not make it separetely so that u can use it other files as well

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/fi_ass2_rohan_login.dart
> +    Widget BtnContainer1 = Padding(
make a seperate widget / class, and pass them login/sign up, backgroundColor etc as property. Follow DRY (Don't repeat yourself)

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/profile/fi_ass2_rohan_profile.dart
> +              const FiAssRohanPart1(),
Please use better names that define what the widget is, I can't really understand what part1 is

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/profile/widgets/fi_ass_rohan.part3.dart
> +class _FiAssRohanPart3State extends State<FiAssRohanPart3> {
Adding a comment for the whole file, do not use padding for spaces

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/profile/widgets/fi_ass_rohan_part1.dart
> +class FiAssRohanPart1 extends StatelessWidget {
Please change this name to something like

```ProfileHeader```

You will add format as well

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/profile/widgets/fi_ass_rohan_part2.dart
> +  final String t1;
please name variables properly,

2023-07-21 10:15 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/profile/widgets/fi_ass_rohan_part4.dart
> +class FiAssRohanPart4 extends StatelessWidget {
Widget name should be proper

2023-07-23 17:05 UTC, ahmadexe requested changes

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Screens/fi_a2_rohan_home.dart
> +              padding: const EdgeInsets.only(left: 12, right: 12),
Use instead
```EdgeInsets.symmetric(horizontal: 12)```

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Screens/fi_a2_rohan_home.dart
> +                      decoration: BoxDecoration(
Either use this or the clipRRect below,

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Screens/fi_a2_rohan_login.dart
> +          rohanSmallSizedBox5,
Why not make another widget or just use SizedBox instead of using 3 widgets

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Screens/fi_a2_rohan_profile.dart
> +            rohanSmallSizedBox3,
Same as before, you should just make another widget

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Screens/fi_a2_rohan_profile.dart
> +            rohanSmallSizedBox2,
same here

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Screens/profile_widget/fi_a2_rohan_profile_grid.dart
> +  final String path3;
Please use better names, path* does not clear the purpose of this variable

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/Screens/profile_widget/fi_a2_rohan_profile_stats.dart
> +  final String text2;
Please Use descriptive names that describe the variables properly

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/rohan_core/fi_a2_rohan_navigation.dart
> +  List<Widget> screens = const [
Please make this final if this is not updating

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/rohan_core/fi_a2_rohan_navigation.dart
> +  List<IconData> iconitems = [
Please make this final if this is not updating

2023-07-23 17:05 UTC, ahmadexe commented on lib/assesments/assessment_2/fi_ass2_rohan/rohan_core/fi_a2_rohan_navigation.dart
> +      floatingActionButton: Container(
this isn't really a way to make bottom navbar but it's alright for now

2023-07-24 08:38 UTC, merged